# Generated by Django 4.2.13 on 2024-05-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('className', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socky.class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('pending', 'Pending')], max_length=11)),
                ('consNum', models.IntegerField(default=0)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socky.teacher')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socky.student')),
            ],
        ),
    ]
