# Generated by Django 5.0 on 2024-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socky', '0002_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='state',
            field=models.CharField(choices=[('dostupné', 'Dostupné'), ('nedostupné', 'Nedostupné'), ('čakajúce', 'Čakajúce')], max_length=11),
        ),
    ]
