# Generated by Django 5.0 on 2024-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socky', '0003_alter_theme_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='section',
            field=models.CharField(choices=[('problematika voľného času', 'Problematika voľného času'), ('matematika, fyzika', 'Matematika, fyzika'), ('chémia, potravinárstvo', 'Chémia, potravinárstvo'), ('biológia', 'Biológia'), ('životné prostredie, geografia, geológia', 'Životné prostredie, geografia, geológia'), ('zdravotníctvo a farmakológia', 'Zdravotníctvo a farmakológia'), ('pôdohospodárstvo (poľnohospodárstvo, lesné a vodné hospodárstvo)', 'Pôdohospodárstvo (poľnohospodárstvo, lesné a vodné hospodárstvo)'), ('cestovný ruch, hotelierstvo, gastronómia', 'Cestovný ruch, hotelierstvo, gastronómia'), ('strojárstvo, hutníctvo, doprava', 'Strojárstvo, hutníctvo, doprava'), ('stavebníctvo, geodézia, kartografia', 'Stavebníctvo, geodézia, kartografia'), ('informatika', 'Informatika'), ('elektrotechnika, hardware, mechatronika', 'Elektrotechnika, hardware, mechatronika'), ('história, filozofia, právne vedy', 'História, filozofia, právne vedy'), ('tvorba učebných pomôcok, didaktické technológie', 'Tvorba učebných pomôcok, didaktické technológie'), ('ekonomika a riadenie', 'Ekonomika a riadenie'), ('teória kultúry, umenie, umelecká, odevná tvorba', 'Teória kultúry, umenie, umelecká, odevná tvorba'), ('pedagogika, psychológia,  sociológia', 'Pedagogika, psychológia,  sociológia')], max_length=64, null=True),
        ),
    ]
